### PR TITLE
Add good message

### PR DESCRIPTION
**Pull request by JasonDahn**
Add a good message for tasks that are not on the bad list

### CODE REVIEW

**Comment by jdkleuver** [comment]
Could you add a checkbox that defaults to False to enable the good message? So that current users won't have an unexpected change when the plugin updates.

**Comment by JasonDahn** [comment]
Absolutely, done :)

**Comment by jdkleuver** [comment]
Looks good, I'll double check that it works properly once I have access to a computer

**Comment by jdkleuver** [comment]
I appreciate why you've renamed the `message` key to `badMessage`, unfortunately I think this would cause existing plugin users to lose their custom messages. I'd prefer if you could change the keyName back to `message` to avoid this.

I've just checked it on my computer, so should be good to merge after this change.

**Comment by JasonDahn** [comment]
Great point I definitely don't want to change the experience for any existing users. I reverted the key name back to `message`

**Pull request merged**
